baseURL = 'https://crazy-a89.github.io/blog/'
locale = 'en-us'
title = '博客'
theme = 'hugo-coder-main'
[caches]
    [caches.images]
        dir = ':cacheDir/images'
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]

        unsafe = true

[params]
  author = "Penguin"
  info = ["Penguin的博客", "去码头整点薯条"]
  avatarurl = "images/penguin.jpg"
  colorScheme = "auto"
  hideColorSchemeToggle = false
  maxSeeAlsoItems = 5
  customSCSS = ["sses/custom.css"]

[[menu.main]]
  name = "文章"
  weight = 1
  url = "/posts/"
